sdsc-ordes/modos-api

.github/workflows/docker-publish.yml
Include a ci workflow to automatically build the __client docker__ image and push it to ghcr.
This workflow should:
1. always add `latest` tag.
2. add modo-api version as tag upon releases
3. run on push to main, releases and changes in `Dockerfile` or `pyproject.yaml` in PRs
__Ops__: For testing it will currently also run on push to this branch (`feat/ci_docker_build`). 
The output of the last run can be found at https://github.com/sdsc-ordes/modo-api/actions/runs/8245306630 
`feat/ci_docker_build` should be removed before merge:
```sh
push:
branches:
- main
- feat/ci_docker_build
```
=> ci: docker build

deploy/nginx/default.conf.template
The [`client_max_body_size`](http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) in nginx is set to 1MB by default. This prevents uploading genomic files, which are normally several orders of magnitude larger.
This PR disables ths limit.
Successfully uploaded a 50GB CRAM file on a test deployment with this fix.
=> fix(deploy): disable body size limit in nginx

deploy/htsget/Dockerfile
htsget minimum supported rust version (msrv) is now 1.75, but our htsget service used 1.74 as the base layer.
This PR pins htsget to the latest release and bumps the MSRV in our base layer.
=> fix(server): pin htsget version + bump msrv

deploy/modos-server/server.py
The modo server did not register MODOs created after startup. This was due to the s3Fs object caching the filesystem state on instantiation by default.
This adds the `refresh=True` option to always refresh the filesystem when the server receives http requests.
Fixes #59
=> fix(server): reload minio filesystem for each server query

modos/api.py, modos/cram.py, modos/helpers.py, tests/conftest.py, tests/test_api_local.py, tests/test_api_remote.py, tests/test_cli_local.py
Automatically copy the corresponding index file together with any file that is copied into the modo
- Genomic file formats are structured in an Enumeration `GenomicsFileFormat`
- Corresponding index file suffixes can be derived from a `GenomicsFileFormat`
- Index files (same name as the genomics file +  index suffix) are automatically copied into modo.
- `FileNotFoundError` for missing index
- `modos.helpers.get_fileformat()` was replaced to be consistent
- Further refactoring of cram streaming
=> fix: auto upload cram index

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/feature-request.yml
Adds issue templates for bug reports and feature requests.
These templates use [github issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) as they are mainly targeting external contributor/user and are not so much intended for internal issues.
=> chore: add issue templates for feature requests and bug reports.

.prettierrc, README.md, deploy/README.md, docs/changelog-link.md, docs/index.md, docs/intro/background.md, docs/intro/quickstart.md, docs/tutorials/modo_access.md, docs/tutorials/modo_arrays.md, docs/tutorials/modo_provider.md, docs/tutorials/modo_remote.md, docs/tutorials/tutorials.md
Format all markdown docs with `prettier`.
- All markdown documents should be formatted. I choose normally `prettier` because there is no better easier tool out there which works nicely. It adheres to `CommonMark` etc. Ok there is `pandoc` and other formatters. We can discuss that in BPA for language guidlines on `docs` maybe.
=> docs: Format markdown documents

data/ex/data.zarr/.zattrs, data/ex/data.zarr/.zmetadata, data/ex/data.zarr/assay/assay1/.zattrs, data/ex/data.zarr/data/calls1/.zattrs, data/ex/data.zarr/data/demo1/.zattrs, modos/api.py, modos/helpers.py, tests/test_api_local.py, tests/test_api_remote.py, tests/test_cli_local.py
Use consistent ids across modos-api. 
- use "full_id" `/element_type/element_id` when returning any element id and within any relationship declaration (`modos.metadata()`, `has_part` relationships,`part_of` relationships)
- adapt tests
- adapt default uri in `modos.knowledgegraph`
=> fix: consistent ids

modos/api.py
Automatically update modos `last_update_date` attribute upon:
- `modo.add_element()`
- `modo.remove_element()`
- `modo.update_element()`
https://github.com/sdsc-ordes/modos-api/issues/48 also includes to autofill the `last_update_date` and `creation_date`, if not provided by the user. This is already provided by `modos.api` and `modos.cli`. The only use case when it has to be provided is `build_modo_from_file()`. It would be nice to also make it optional there, but it collides with `linkml_runtime.loaders`, which expect both attributes as non-optional. I think changing this is not worth the benefit, as both attributes only need to be specified once and I would consider this part as `wontfix`.
=> feat: auto update last_update_date attr

modos/api.py, modos/cram.py, modos/helpers.py
This PR ensures records streamed from htsget match the query region by applying lazy filter on client side. This is because the htsget server only selects record at the bgzf block level, resulting in out-of-query records.
This is a quickfix and the streaming code will need refactor as it is not maintainable nor efficient.
Fixes #51
=> fix: client-side region-filter on htsget streams

modos/api.py, modos/helpers/schema.py, tests/test_api_local.py
So far `update_element()` did not overwrite existing metadata attributes, but only add new attributes that did not exist before.
An example to reproduce this is in https://github.com/sdsc-ordes/modos-api/issues/81
The reason for this is that we only compare new vs existing keys here:
```python
new_items = {
field: value
for field, value in new._items()
if field not in attrs.keys()
and field != "id"
and value is not None
and value != []
}
```
The problem when comparing values is that values in new._items() are sometimes from linkml models (`modos_schema.datamodel`) and can contain descriptions etc, so that they can not easily be compared.
Example:
```python
>>> import modos_schema.datamodel as model
>>> sample = model.Sample(id="sample1", collector= 'Foo university', sex= 'Female')
>>> …
```
=> fix(api): update new values in update_element

modos/cli.py
Adds a stream command that sends the binary data from a remote HTS file into stdout. This enables piping modos genomic files into other tools.
Questions:
* Currently only works with remote files. Does it make sense to make it work with local files as well?
* Currently takes eleemnt_id as input. Would it make more sense to take a file path or not?
=> feat(cli): stream command

modos/api.py, modos/cli.py
Add cli function to group update modo based on a yaml file. By default, this function will update existing elements, add new elements and remove elements that are not specified in the yaml, but part of modo. `--no-remove` flag can be set to prevent deletion of elements.
- I think `modo.from_file()` should have the same behavior and by default remove objects that are not specified in the yaml any longer. 
- I realized that there is no need to specify the modo itself in the yaml file, as modo just needs the `object_directory` and we require `object_directory()` as input argument anyways.
- I did not add an `--element-id` flag, as it is the same as running `--no-remove` with a yaml only specifying the element to change.
I realized that  `modo.update_element()` does accept a `source-file` or …
=> feat(cli): update modo from yaml file

deploy/docker-compose.yml, deploy/modos-server/server.py, modos/__init__.py, modos/api.py, modos/cli.py, modos/genomics/htsget.py, modos/remote.py, modos/storage.py, poetry.lock, pyproject.toml, tests/conftest.py, tests/test_api_remote.py
**Objective:**
Allows users to always specify the same modos server endpoint. Underlying htsget/s3 endpoints are auto-detected internally by querying the modos server.
For testing / advanced usage, a `services` option is still exposed in the API to bypass this and explicitely provide service endpoints.
**Notes**
* As every command in the CLI was copy-pasting the `s3_endpoint` option, this PR removes it in favor of a top-level `endpoint` flag that is inherited by all commands (through typer.Context).
* `endpoint` option can also read from the environment variable `MODOS_ENDPOINT`.
* the docker compose config used a static network ip. This was only needed because we passed the S3_LOCAL_URL to htsget instead of S3_PUBLIC_URL (by mistake). Fixing the env var makes the static IP unnecessary, …
=> feat: streamline remote options

README.md, docs/tutorials/modo_access.md, modos/rdf.py
The `schema` prefix is assigned by default by rdflib to **https**://schema.org.
Unfortunately, linkml cannot use **https**://schema.org and assigns the schema namespace to **http**://schema.org
As modos inherits **http** from linkml, all conversions to rdflib resulted in using the automatically assigned `schema1` prefix.
This PR overrides the default rdflib assignment of `schema` so that turtle serialization and SPARQL queries on modos objects can use the `schema` prefix.
=> fix(rdf): schema.org prefix

.github/workflows/poetry-publish.yml, .github/workflows/poetry-pytest.yml, .github/workflows/poetry-test-publish.yml, docs/conf.py, pyproject.toml
Two new github action workflows with 2 jobs each:
- `poetry-publish`: 1. build modos-api and 2. publish at pypi, triggered on published releases
- `poetry-test-publish`:  1. build modos-api and 2. publish at test-pypi, manually triggered by workflow dispatch
The publishing job uses trusted publisher management for authentication, which requires write permission. To not elevate privileges building and publishing were separated into two different ci-jobs as recommended.
So far only `poetry-test-publish` was run (see [output](https://github.com/sdsc-ordes/modos-api/actions/runs/10265083314)) and tested. Both workflows are build analogous, but I think we have to wait for the next release to check `poetry-publish`?
=> ci: build and publish at pypi/test-pypi

modos/helpers/schema.py
:warning: This is a workaround a linkml problem (or mis-use?), and I'm not sure it should be merged.
**Context**
`schema:identifier` is marked as mandatory in the schema, and appears as `minCount 1` in the modos-schema schacl rules, however when serializing our metadata graph to RDF, the resulting instances do not have any `schema:identifier` triple, meaning we are not compliant with the shapes.
**Proposed change**
This PR attempts to solve that by injecting the relevant triple into instance graphs upon serialization. The implementation is sort of convoluted and I wish there was a better way.
**Notes**
The identifier property is also not very useful as-is; a copy of the subject URI. In modos-schema, we require schema:identifier to be a URI, but I wonder if we should relax this requirement …
=> fix(rdf): inject schema:identifier

modos/api.py, modos/cli.py
Quality of life feature to target a specific element when inspecting an object:
CLI:
```shell
$ modos show data/ex sample/sample1
sample/sample1:
'@type': Sample
cell_type: astrocyte
description: Dummy sample for tests
name: Sample 1
sex: Male
source_material: brain tissue
$ modos show --zarr data/ex assay
assay
└── assay1
```
API:
```python
m = MODO('data/ex')
m.show_contents('sample/sample1')
m.list_arrays('data')
```
**Limitations**
Does not work with the `--files` option, as I was not sure whether it makes sense; e.g. should this list the index files (.crai, .csi, ...), should we list files directly linked to the element, or also recursively (sample1 -> data1 -> file).
=> feat(cli, api):show only target element

deploy/docker-compose.yml, deploy/htsget/docker-entrypoint.sh, modos/genomics/htsget.py
This PR affects bugs that prevented htsget from connecting to the minio s3 bucket:
* fixed malformed URL when no trailing slash was present on the input enpoint
* Fixed compose environment variables to connect htsget to s3 using the service identifier unless S3_LOCAL_URL is set
* configure htsget to use path-style bucket by default
=> fix(htsget): htsget minio connection

deploy/.example.env, deploy/README.md, deploy/docker-compose.yml, deploy/nginx/default.conf.template, docs/development_guide.md
**Context**
The latest changes in the docker compose setup broke the connection between htsget and minio services. This is because the client had no access to the internal minio service address, which htsget hardcodes in the json returned to the client.
Attempts to route htsget requests through the reverse proxy were not successful because the canonical s3 URL (including hostname) [is used when deriving s3 keys](https://docs.aws.amazon.com/IAM/latest/UserGuide/create-signed-request.html) for signing requests. As the s3 hostname was different between the client (reverse proxy) and htsget (compose service), s3 signatures were invalid.
The (failed) request flow for streaming data looked something like this:
```mermaid
sequenceDiagram
client->>nginx: http://localhost/htsget/...
nginx …
```
=> fix(deploy): htsget networking

Makefile
Adds a `make deploy` rule to dynamically inject local IP address in environment when deploying compose
=> chore: makefile recipe for deployment

Dockerfile, modos/cli.py, modos/codes.py
When using code search locally, loading the terminologies over the network can take up to 30s.
This PR implements caching so that this only happens the first time a terminology is used.
On subsequent loads, they are loaded from cache, which takes about 1s.
Caching logic is implemented in fuzon, and each terminology has one cache entry whose key is determined by its URL, last modified datetime and/or ETag checksum if available.
=> perf: use fuzon cache with CodeMatcher

poetry.lock, pyproject.toml
Bump modos schema to 0.2.1 to rely on linkml 1.8.4 and support python 3.13
=> chore(deps): bump modos-schema to 0.2.1

modos/api.py, modos/genomics/formats.py, modos/helpers/schema.py, modos/storage.py, poetry.lock, pyproject.toml, tests/test_api_local.py, tests/test_api_remote.py
Depends on: https://github.com/sdsc-ordes/modos-schema/pull/21
1. Fix https://github.com/sdsc-ordes/modos-api/issues/116 to update a data_path on an existing object when read from file.
2. Check and update files, that are part of modos, if the source-file has changed 
- add data-file checksum attribute by calculating the `blake2B checksum` to a `DataEntity` when it is added and has a linked file. 
- `modos.update_element()` accepts `source_file` and `part_of` args (consistent `modos.add_element()`). 
-  `modos.update_element()` moves associated files, if the data_path attribute has changed
- `modos.update_element()` updates associated files, if the `data_checksum` differs 
- `modos.storage.Storage` class includes a move method
- `modos.update_element()`: index files related to genomic …
=> fix(api): update data path

deploy/.example.env, deploy/README.md, deploy/docker-compose.yml, deploy/nginx/default.conf.template, deploy/refget/Dockerfile, deploy/refget/config.properties.template, deploy/refget/docker-entrypoint.sh, modos/genomics/refget.py, modos/remote.py, poetry.lock, pyproject.toml
Deploy [refget](https://samtools.github.io/hts-specs/refget.html) service to give hash-identifier based access to reference sequences as part of modos deployment
- add a new public bucket (genome-references) to minio deployment
- deploy [refget-cloud](https://github.com/ga4gh/refget-cloud) with the genome-references bucket as source
- generate sequence hashes via [gtars](https://github.com/databio/gtars)
- build minimal metadata object as described in refget specs
- upload reference sequences, their metadata objects and alternative ids to s3 bucket with required `Content-Type` and `website-rdirect-location` header (see [refget-cloud s3 docs](https://github.com/ga4gh/refget-cloud/blob/master/docs/guides/DataSourceAwsS3.md); this replaces refget-compliant sequence upload via …
=> feat(deploy): setup refget service

modos/api.py, modos/cli.py
Add force flag to `modos update`. See https://github.com/sdsc-ordes/modos-api/issues/114
Replace `--no-remove` with `--force` flag in `modos update`. Instead of explicitly allowing to __not__ remove missing elements, this PR implements the following logic, if an existing element is missing from `config_file`:
- prompt for explicit deletion by default 
- add --force flag to skip prompts
=> feat(cli): update prompts for removal of missing config elements

.github/workflows/docker-publish.yml
* Fetch version from `__init__.py` instead of `pyproject.toml`
* Allow pushing docker images with version tags manually using workflow dispatch (in addition to on release)
=> ci(docker): fix version parsing  on release

src/modos/genomics/formats.py, src/modos/helpers/schema.py
- check if files are encrypted through file header bytes.
- handles file suffixes unambigously (`add` or `remove` suffix instead of `toggle`).
- (decryption): raise error if c4gh encrypted, but no `c4gh`suffix. This should not happen. Modos and c4gh libs add `.c4gh` as suffix, but this is no strict requirement.
- only checks for crypt4gh encryption. I think that is reasonable as we only support c4gh encryption
=> fix(api): sequential encryption

src/modos/cli.py
Fixes a crash when passphrase is read from a file in `modos decrypt`
=> fix(cli): syntax when reading passphrase from file

.github/workflows/docker-publish.yml, tools/deploy/modos-server/Dockerfile
* Fixes tag extraction in docker publish CI workflow
* Bumps the tag of the base layer for the server image
=> ci(docker): fix release tag

README.md
Fixes a broken link to the configuration and deploy instructions from the root README.
=> docs: fix link to deploy from root README

tools/deploy/fuzon/Dockerfile, tools/deploy/fuzon/config.json.template, tools/deploy/modos-server/Dockerfile
This PR adds support for air gapped deployments:
* run uv in offline mode in modos-server.
* prefetch assets (terminologies) at build time with fuzon.
=> feat: compatibility with air-gapped deployments

pyproject.toml, src/modos/codes.py, src/modos/prompt.py, uv.lock
This PR makes pyfuzon a core dependency on all platform except for windows.
When neither a fuzon server, nor a pyfuzon client are available (on windows), the CLI gracefully falls back to plain-text interface without auto-suggestions, instead of crashing.
=> feat(fuzon): cli fallback without autocomplete

src/modos/genomics/formats.py, src/modos/genomics/htsget.py
"Streaming" in python did not work for vcf files because:
- `to_pysam` did not extract the full suffix for gzipped files (e.g. `.vcf.gz` --> only `.gz`).  Thus tmp-files received the wrong suffix and failed.
- pysam raised a TypeError in the `VariantFile` call because we parsed `reference_filename` as part of **kwargs. `reference_filename` is only a valid parameter of `AlignmentFile`.
```python
from modos.api import MODO
url = "https://modos.dscompute.ch"
modo = MODO(path = "s3://modos-demo/AIP", endpoint = url)
test=modo.stream_genomics(file_path = 'modos-demo/AIP/AIP.vcf.gz', region = "chromosome7:798425")
for rec in test:
print(rec)
``
=> fix: vcf streaming with pysam

docs/tutorials/modo_remote.md, pyproject.toml, src/modos/cli/codes.py, src/modos/cli/main.py, src/modos/cli/remote.py, src/modos/storage.py, tests/test_cli_remote.py, uv.lock
Adds support for s3 credentials through the command line interface via environment variables.
The default behavious in modos until now was to pass `{"anon": True}` to the s3fs client.
This PR chnages the default to False so that it automatically scans standard AWS S3 environment variables.
Anonymous access is still possible through a new `--anon` toplevel flag on the CLI.
=> feat(cli): pass s3 credentials via env
